# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

opt_out_usage

default_platform(:android)

platform :android do
  desc "Test app"
  lane :app_test do
    gradle(
      task: "app:test"
    )
  end

  desc "Publish app"
  lane :app_publish do
    gradle(
      task: "app:bundleRelease",
      properties: {
        "versionPatch" => ENV["BUILD_NUMBER"],
        "keystorepath" => ENV["KEYSTORE_PATH"],
        "keystorepassword" => ENV["KEYSTORE_PASSWORD"],
        "keypasswordjmriroster" => ENV["KEYSTORE_PASSWORD_JMRI_ROSTER"]
      }
    )
    # upload_to_play_store
  end


  desc "Test lib"
  lane :lib_test do
    gradle(
      task: "lib:test"
    )
  end

  desc "Publish lib artifact"
  lane :lib_publish do
    gradle(
      task: "lib:publishReleasePublicationToGithubPackagesRepository",
      properties: {
        "versionPatch" => ENV["BUILD_NUMBER"],
        "githubuser" => ENV["GITHUB_USER"],
        "githubtoken" => ENV["GITHUB_TOKEN"]
      }
    )
  end
end
