# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

opt_out_usage

default_platform(:android)

platform :android do
  desc "Test app"
  lane :app_test do
    gradle(
      task: "app:test"
    )
  end

  desc "Build apks for UI tests"
  lane :app_build_for_ui_test do
    gradle(
      task: "app:assemble",
      build_type: 'Debug'
    )
    gradle(
      task: "app:assemble",
      build_type: 'AndroidTest'
    )
  end

  desc "Capture screenshots"
  lane :app_capture_screenshots do
    screengrab(
      use_adb_root: true
    )
  end

  desc "Publish app"
  lane :app_publish do
    gradle(
      task: "app:bundleRelease",
      properties: {
        "versionPatch" => ENV["BUILD_NUMBER"],
        "keystorepath" => ENV["KEYSTORE_PATH"],
        "keystorepassword" => ENV["KEYSTORE_PASSWORD"],
        "keypasswordjmriroster" => ENV["KEYSTORE_PASSWORD_JMRI_ROSTER"]
      }
    )
    upload_to_play_store(
      track: "alpha",
      aab: ENV["AAB_PATH"],
      skip_upload_apk: true,
      json_key_data: ENV["SERVICE_ACCOUNT_JSON"]
    )
  end


  desc "Test lib"
  lane :lib_test do
    gradle(
      task: "lib:test"
    )
  end

  desc "Publish lib artifact"
  lane :lib_publish do
    gradle(
      task: "lib:publishReleasePublicationToGithubPackagesRepository",
      properties: {
        "versionPatch" => ENV["BUILD_NUMBER"],
        "githubuser" => ENV["GITHUB_USER"],
        "githubtoken" => ENV["GITHUB_TOKEN"]
      }
    )
  end
end
