name: cicd-app

on:
  push:
    branches:
      - 'master'
    paths:
      - 'app/**'
      - '.github/workflows/cicd-app.yml'

jobs:
  test_app:
    name: Test app
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run unit tests
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'android app_test'

  publish_app:
    name: Publish app
    runs-on: macos-latest
    # needs: test_app
    if: "!contains(github.event.head_commit.message, '#skip-app-publish')"
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Update Bundle
        run: bundle update
      - name: Deploy keystore
        run: echo '${{ secrets.RELEASE_KEYSTORE }}' | base64 -d > $ORG_GRADLE_PROJECT_keystorepath
        env:
          ORG_GRADLE_PROJECT_keystorepath: ${{ github.workspace }}/release.jks
      
      - name: Build apks for UI tests
        run: bundle exec fastlane android app_build_for_ui_test
      
      - name: Capture app screenshots
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          profile: Nexus 6
          script: ./app/src/androidTest/enable_demo_mode.sh && bundle exec fastlane android app_capture_screenshots

      - name: Build and publish app
        run: bundle exec fastlane android app_publish
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          KEYSTORE_PATH: ${{ github.workspace }}/release.jks
          KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          KEYSTORE_PASSWORD_JMRI_ROSTER: ${{ secrets.RELEASE_KEYSTORE_ALIAS_JMRI_ROSTER_PASSWORD }}
          AAB_PATH: ${{ github.workspace }}/app/build/outputs/bundle/release/app-release.aab
          SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}