name: cicd-lib

on:
  push:
    branches:
      - 'master'
    paths:
      - 'lib/**'

jobs:
  test_lib:
    name: Test lib module
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run unit tests
        run: bash ./gradlew lib:test --stacktrace
        env:
          ORG_GRADLE_PROJECT_githubuser: ${{ secrets.GH_USER }}
          ORG_GRADLE_PROJECT_githubtoken: ${{ secrets.GH_TOKEN }}
          ORG_GRADLE_PROJECT_keystorepath: release.jks
          ORG_GRADLE_PROJECT_keystorepassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          ORG_GRADLE_PROJECT_keypasswordjmriroster: ${{ secrets.RELEASE_KEYSTORE_ALIAS_JMRI_ROSTER_PASSWORD }}

  publish_lib:
    name: Publish lib artifact
    runs-on: ubuntu-18.04
    needs: test_lib
      if: "!contains(github.event.head_commit.message, '#skip-lib-publish')"
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish artifact
        run: bash ./gradlew lib:publishReleasePublicationToGithubPackagesRepository -P versionPatch=${{ github.run_number }}
        env:
          ORG_GRADLE_PROJECT_githubuser: ${{ secrets.GH_USER }}
          ORG_GRADLE_PROJECT_githubtoken: ${{ secrets.GH_TOKEN }}
